name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.9.3
      with:
        args: --exclude-mail
        fail: true
  html-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: ./
